//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 07:12:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mngt.io/services/transactions", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.mngt.services.transactions;
